---
- name: Initialize cluster
  command: >
    kubeadm init
    --pod-network-cidr=192.168.0.0/23
    --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube dir for root
  file:
    path: /root/.kube
    state: directory
    mode: "0700"

- name: Copy kubeconfig for root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: "0600"

- name: Install Calico
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/calico.yaml
  environment:
    KUBECONFIG: /root/.kube/config

- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_command_raw

- name: Store join command as fact
  set_fact:
    join_command: "{{ join_command_raw.stdout }}"
