---
- name: Skapa en ny användare
  ansible.builtin.user:
    name: labbuser
    shell: /bin/bash
    create_home: true
    state: present

- name: Lägg till användare i sudo-gruppen
  ansible.builtin.user:
    name: labbuser
    groups: sudo
    append: true

- name: Kontrollera att användaren skapades
  ansible.builtin.debug:
    msg: "✅ Användaren labbuser är skapad!"