apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: default
  labels:
    app: webapp
spec:
  serviceAccountName: vulnerable-sa
  containers:
  - name: webapp
    image: python:3.11-slim
    command: ["/bin/sh", "-c"]
    args:
      - pip install flask --quiet && python /app/webapp.py
    ports:
    - containerPort: 5000
    env:
    - name: DB_PASSWORD
      value: "SuperHemligt123!"
    - name: API_KEY
      value: "sk-prod-abc123xyz789"
    volumeMounts:
    - name: webapp-script
      mountPath: /app
  volumes:
  - name: webapp-script
    configMap:
      name: webapp-script
