---
- name: Common k8s prerequisites
  hosts: control_plane:workers
  become: true
  roles:
    - k8s-common

- name: Initialize control plane
  hosts: control_plane
  become: true
  roles:
    - k8s-master

- name: Join workers
  hosts: workers
  become: true
  roles:
    - k8s-worker

- name: Apply vulnerable configurations
  hosts: control_plane
  become: true
  roles:
    - k8s-vulnerable

- name: Install security tools
  hosts: control_plane
  become: true
  roles:
    - k8s-security-tools