---
- name: Skriv secrets till vault
  uri:
    url: "http://127.0.0.1:{{ vault_port }}/v1/secret/data/{{ item.key }}"
    method: POST
    body_format: json
    body:
      data: "{{ item.value }}"
    headers:
      X-Vault-Token: "{{ vault_init.root_token }}"
    status_code: [200, 204]
  loop: "{{ vault_secrets | dict2items }}"
  no_log: true
