---
- name: Skriv secrets till vault
  community.hashi_vault.vault_kv2_write:
    url: "http://127.0.0.1:{{ vault_port }}"
    token: "{{ vault_init.root_token }}"
    engine_mount_point: secret
    path: "{{ item.key }}"
    data: "{{ item.value }}"
  loop: "{{ vault_secrets | dict2items }}"
  no_log: true
