---
- name: Install dependencies
  apt:
    name: [gpg, curl]
    state: present
    update_cache: true

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Install vault
  apt:
    name: vault
    state: present


