---
- name: Installera UFW
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Tillåt SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Tillåt HTTP
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Aktivera brandväggen
  community.general.ufw:
    state: enabled

- name: Kontrollera att UFW är aktivt
  ansible.builtin.debug:
    msg: "✅ Brandväggen är aktiv!"