---
- name: Kopiera deployment.yaml
  copy:
    src: deployment.yaml
    dest: /home/ansible/deployment.yaml
    owner: ansible
    mode: "0644"

- name: Kopiera service.yaml
  copy:
    src: service.yaml
    dest: /home/ansible/service.yaml
    owner: ansible
    mode: "0644"

- name: Applicera Flask deployment
  command: kubectl apply -f /home/ansible/deployment.yaml
  environment:
    KUBECONFIG: /home/ansible/.kube/config

- name: Applicera Flask service
  command: kubectl apply -f /home/ansible/service.yaml
  environment:
    KUBECONFIG: /home/ansible/.kube/config