---
- name: Konfigurera ansible control node
  hosts: localhost
  connection: local
  become: true
  roles:
    - common

- name: Bootstrap HashiCorp Vault
  hosts: vault
  become: true
  roles:
    - common
    - vault

- name: Konfigurera Vault AppRole för k8s
  hosts: vault
  become: true
  roles:
    - vault-config

- name: Common k8s prerequisites
  hosts: control_plane:workers
  become: true
  roles:
    - common
    - k8s-common

- name: Initialize control plane
  hosts: control_plane
  become: true
  roles:
    - k8s-master

- name: Hämta Vault secrets till k8s-master
  hosts: control_plane
  become: true
  roles:
    - k8s-vault

- name: Join workers
  hosts: workers
  become: true
  roles:
    - k8s-worker

- name: Driftsätt sårbar webbapp
  hosts: control_plane
  become: true
  tags: vulnerable
  roles:
    - k8s-vulnerable
